# Generated by Django 5.0.3 on 2025-12-17 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_list', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todolist',
            old_name='modified_at',
            new_name='updated_at',
        ),
    ]
