# Generated by Django 5.0.3 on 2025-12-17 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_list', '0002_rename_modified_at_todolist_updated_at'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Todolist',
            new_name='Todo',
        ),
    ]
